apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog-app
  name: my-deploy-blog
  namespace: ns-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app
          image: mskr7/mkadir-blogapp:latest
          resources:
            limits:
              memory: 300Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.3"
          ports:
            - containerPort: 8080 # The port your application is listening on. match with targetPort in service.yaml and docker webserver exposed port
